### PR TITLE
Fixed a small typo.

### PR DESCRIPTION
**Pull request by drguildo**

### CODE REVIEW

**Comment by drguildo** [comment]
That's really strange. Can you see it at 456e1e6be52c5618ed6d55fca4bbb34a41ed6bdb?

**Comment by shiffman** [comment]
Yes, this is what I'm seeing. . . I keep starting at it, but I can't find the typo.  What is it?

screen shot 2016-09-18 at 9 51 11 pm

**Comment by drguildo** [comment]
`such as in the case of see gravitational attraction` → `such as in the case of gravitational attraction`

**Comment by shiffman** [comment]
Aha, all is right with the world again, thank you!!

**Pull request merged**
