### PR TITLE
Minor textual (and image) improvements to chapters 1-8.

### PR DESCRIPTION
**Pull request by jschulenklopper**
Every commit in this PR has a description of the changes per commit / chapter.

### CODE REVIEW

**Comment by jschulenklopper** [comment]
Commit 44c7169 closes issue #54.

**Comment by jschulenklopper** [comment]
Commit 7db0e39 closes #52, "walk four steps north" instead of "five".

**Comment by shiffman** [comment]
Wonderful, amazing, thank you!!  For the illustration fixes, I'll need to update the original AI files.  Will open a new issue to track and make sure I do.

**Comment by jschulenklopper** [comment]
> For the illustration fixes, I'll need to update the original AI files.

Oh, OK. Couldn't find those in the repository (or didn't look well enough), so I edited the images directly.

**Comment by shiffman** [comment]
Yeah, they are large files so I didn't include them on github.  I will revisit adding them as I do some more cleanup work.

**Pull request merged**
