### PR TITLE
Updating css to work with magicbook v2

### PR DESCRIPTION
**Pull request by nelliemckesson**
Updating CSS and testing with the new magicbook :)

### CODE REVIEW

**Comment by shiffman** [comment]
Going through this now, thank you so excited! I tagged @runemadsen as a reviewer, but no worries if you are super busy Rune, more of an FYI!

**Comment by shiffman** [comment]
Ok, I built the book with your changes @nelliemckesson, this is incredible work! I can't believe how *finished* it looks! I'll wait a little bit to see if @runemadsen has any comments and then will go ahead and merge. A few questions picking up on #63 and #6.

1. All the numbering (examples, sections, etc.) is hard-coded. I'm fine with keeping it this way but curious what is currently possible with magic book and what we should plan for?

2. Looks like the only missing piece is the index! @runemadsen I forget where we last left this, is there something for index generation in magic book or not yet?

@nelliemckesson perhaps a good next step is sorting out the HTML generation and seeing if we can get an updated version of the book on http://natureofcode.com? The complicating factor here is running the JS versions of the examples rather than rendering images.

I guess now I actually have to start doing my rewrites! 😅

**Comment by nelliemckesson** [comment]
@shiffman sounds good! I'll work on the HTML generation this week--I'll probably have a bunch of questions for you once I start poking at it. Re: section numbering, I think we should be able to do that via CSS/counters (unless @runemadsen has something special baked into magicbook), though I haven't tested yet, so don't quote me on that. But I can try a quick test with that this week as well, so that maybe you won't have to keep track of all the numbering yourself.

**Comment by shiffman** [comment]
Merging!!! 🎉🎉🎉

**Pull request merged**
